name: Crawl blocked domains from Greatfire Analyzer
on:
  schedule:
    - cron: "0 20 */16 * *"
  push:
    tags:
      - "v*"
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: "^1.14.7"

      - name: Set $GOPATH and more variables
        run: |
          echo "::set-env name=RELEASE_NAME::Released on $(date +%Y%m%d%H%M)"
          echo "::set-env name=TAG_NAME::$(date +%Y%m%d%H%M)"
          go env -w GO111MODULE=on
        shell: bash

      - name: Checkout codebase
        uses: actions/checkout@v2.3.3

      - name: Get project dependencies & run
        run: |
          go mod download
          go run *.go

      - name: Move file to publish directory
        run: |
          mkdir -p ./publish
          install -p domains.txt raw.txt ./publish/

      - name: Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push assets to "release" branch
        run: |
          cd publish
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
